### ISSUE TITLE
Questions about the Ablation Study

### ISSUE THREAD

**Issue by sunxiaoyao-git** [usail-hkust/t-PatchGNN#6]
Hello, this is a great work!
About the Ablation Study, I have two questions. 
1. In your paper, which result in Table 2 is the finding -  "However, we observe that the dynamic patch embedding plays a significant role on human motion and climate forecasting, which indicates the variables’ correlation in these tasks can usually dynamically vary along with time." refers to ? **w/o PE** or **w/o Transformer**?
2. If I want to do the same ablation as you designed, what code in your current repository should I change?

Thank you.

**Comment by willzhang3** [comment]
R1.  This finding corresponds to w/o PE.
R2. The results of w/o PE can be reproduced by removing the code between lines 226-231 in tPatchGNN.py.
